# Generated by Django 5.2.14 on 2026-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_wang_member_userprofile_trial_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='best_memory_steps',
            field=models.IntegerField(default=99999, verbose_name='记忆训练最佳步数'),
        ),
    ]
