# Generated by Django 5.2.14 on 2026-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_best_memory_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='best_minesweeper_time',
            field=models.IntegerField(default=0, verbose_name='黑课最佳成绩(秒)'),
        ),
    ]
