# Generated by Django 5.2.14 on 2026-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_best_minesweeper_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='best_snake_score',
            field=models.IntegerField(default=0, verbose_name='贪吃蛇最高分'),
        ),
    ]
