# Generated by Django 5.2.14 on 2026-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.IntegerField(choices=[(0, '待验证'), (1, '已通过')], default=0),
        ),
    ]
